"""add business model

Revision ID: 1fd21d3760f1
Revises: ffd4ad02c364
Create Date: 2026-02-06 15:39:12.751643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fd21d3760f1'
down_revision: Union[str, Sequence[str], None] = 'ffd4ad02c364'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('slot_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('same_day_cutoff_hour', sa.Integer(), nullable=True),
    sa.Column('business_hours', sa.JSON(), nullable=False),
    sa.Column('services', sa.JSON(), nullable=False),
    sa.Column('deposit_required_after_hour', sa.Integer(), nullable=True),
    sa.Column('deposit_amount', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('bookings', sa.Column('business_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'bookings', 'businesses', ['business_id'], ['id'])
    op.add_column('sessions', sa.Column('business_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'sessions', 'businesses', ['business_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_column('sessions', 'business_id')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'business_id')
    op.drop_table('businesses')
    # ### end Alembic commands ###
