"""add conversation logging tables

Revision ID: c8bbde018466
Revises: 1fd21d3760f1
Create Date: 2026-03-04 14:39:38.013287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c8bbde018466'
down_revision: Union[str, Sequence[str], None] = '1fd21d3760f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('normalized_intent', sa.String(), nullable=True),
    sa.Column('llm_confidence', sa.String(), nullable=True),
    sa.Column('llm_raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fsm_state_before', sa.String(), nullable=True),
    sa.Column('fsm_state_after', sa.String(), nullable=True),
    sa.Column('is_error', sa.Boolean(), nullable=True),
    sa.Column('error_type', sa.String(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_messages_business_id'), 'conversation_messages', ['business_id'], unique=False)
    op.create_index(op.f('ix_conversation_messages_phone_number'), 'conversation_messages', ['phone_number'], unique=False)
    op.create_index(op.f('ix_conversation_messages_session_id'), 'conversation_messages', ['session_id'], unique=False)
    op.create_table('conversation_sessions',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_messages', sa.Integer(), nullable=True),
    sa.Column('booking_created', sa.Boolean(), nullable=True),
    sa.Column('booking_confirmed', sa.Boolean(), nullable=True),
    sa.Column('booking_cancelled', sa.Boolean(), nullable=True),
    sa.Column('booking_rescheduled', sa.Boolean(), nullable=True),
    sa.Column('payment_completed', sa.Boolean(), nullable=True),
    sa.Column('no_show', sa.Boolean(), nullable=True),
    sa.Column('fallback_count', sa.Integer(), nullable=True),
    sa.Column('handoff_count', sa.Integer(), nullable=True),
    sa.Column('avg_latency_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_conversation_sessions_business_id'), 'conversation_sessions', ['business_id'], unique=False)
    op.create_index(op.f('ix_conversation_sessions_phone_number'), 'conversation_sessions', ['phone_number'], unique=False)
    op.create_table('fsm_transitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('from_state', sa.String(), nullable=False),
    sa.Column('to_state', sa.String(), nullable=False),
    sa.Column('trigger_intent', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fsm_transitions_business_id'), 'fsm_transitions', ['business_id'], unique=False)
    op.create_index(op.f('ix_fsm_transitions_session_id'), 'fsm_transitions', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fsm_transitions_session_id'), table_name='fsm_transitions')
    op.drop_index(op.f('ix_fsm_transitions_business_id'), table_name='fsm_transitions')
    op.drop_table('fsm_transitions')
    op.drop_index(op.f('ix_conversation_sessions_phone_number'), table_name='conversation_sessions')
    op.drop_index(op.f('ix_conversation_sessions_business_id'), table_name='conversation_sessions')
    op.drop_table('conversation_sessions')
    op.drop_index(op.f('ix_conversation_messages_session_id'), table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_phone_number'), table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_business_id'), table_name='conversation_messages')
    op.drop_table('conversation_messages')
    # ### end Alembic commands ###
