"""initial schema

Revision ID: ffd4ad02c364
Revises: 
Create Date: 2026-02-06 15:37:14.073708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffd4ad02c364'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('service', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('time', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('calendar_event_id', sa.String(), nullable=True),
    sa.Column('calendar_provider', sa.String(), nullable=True),
    sa.Column('calendar_last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_required', sa.Boolean(), nullable=False),
    sa.Column('payment_status', sa.String(), nullable=False),
    sa.Column('deposit_amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('stripe_checkout_session_id', sa.String(), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(), nullable=True),
    sa.Column('payment_link', sa.String(), nullable=True),
    sa.Column('payment_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_attempt_count', sa.Integer(), nullable=True),
    sa.Column('payment_last_error', sa.String(), nullable=True),
    sa.Column('reminder_24h_sent', sa.Boolean(), nullable=True),
    sa.Column('reminder_2h_sent', sa.Boolean(), nullable=True),
    sa.Column('reminder_confirmed', sa.Boolean(), nullable=True),
    sa.Column('reminder_last_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('no_show_risk', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_phone_number'), 'bookings', ['phone_number'], unique=False)
    op.create_index(op.f('ix_bookings_stripe_checkout_session_id'), 'bookings', ['stripe_checkout_session_id'], unique=False)
    op.create_index(op.f('ix_bookings_stripe_payment_intent_id'), 'bookings', ['stripe_payment_intent_id'], unique=False)
    op.create_table('sessions',
    sa.Column('booking_state', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('last_message_id', sa.String(), nullable=True),
    sa.Column('last_intent', sa.String(), nullable=True),
    sa.Column('last_question', sa.String(), nullable=True),
    sa.Column('pending_service', sa.String(), nullable=True),
    sa.Column('pending_date', sa.String(), nullable=True),
    sa.Column('pending_time', sa.String(), nullable=True),
    sa.Column('pending_booking_id', sa.String(), nullable=True),
    sa.Column('reschedule_target_booking_id', sa.String(), nullable=True),
    sa.Column('reschedule_new_date', sa.String(), nullable=True),
    sa.Column('reschedule_new_time', sa.String(), nullable=True),
    sa.Column('last_reminder_booking_id', sa.String(), nullable=True),
    sa.Column('processed_message_ids', sa.JSON(), nullable=True),
    sa.Column('expired_last_turn', sa.Boolean(), nullable=True),
    sa.Column('expired_from_state', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fail_count', sa.String(), nullable=True),
    sa.Column('handoff_offered', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_sessions_session_id'), 'sessions', ['session_id'], unique=False)
    op.create_table('stripe_webhook_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stripe_webhook_events_event_id'), 'stripe_webhook_events', ['event_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stripe_webhook_events_event_id'), table_name='stripe_webhook_events')
    op.drop_table('stripe_webhook_events')
    op.drop_index(op.f('ix_sessions_session_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_bookings_stripe_payment_intent_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_stripe_checkout_session_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_phone_number'), table_name='bookings')
    op.drop_table('bookings')
    # ### end Alembic commands ###
